spring:
  application:
    name: github-profile-api
  cache:
    type: caffeine

server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never

github:
  api:
    base-url: https://api.github.com
    timeout: 3s
    max-repository-pages: 10
  cache:
    ttl: 5m

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: INFO
    com.branchinterview.githubprofile: INFO
